### ISSUE TITLE
Custom Images with Videos

### ISSUE THREAD

**Issue by jmason03** [timbuckingham/bigtree-media-gallery-field-type#2]
If the item is a video, the image pulled using the API may not meet the size requirements defined in the options. If it does not, it is rejected and there is no way to insert a custom image with a video to take its place.

**Comment by timbuckingham** [comment]
It should be upscaling the video's thumbnail images to the defined minimums. What behavior are you seeing? Is it throwing an error on them?

**Comment by jmason03** [comment]
Well I think part of it is that my minimum requirements are really high for this particular field. But what happens is I enter the YouTube URL and then when I save it I am given the error "Image uploaded (youtube-video-WpWadlgwjeA.jpg) did not meet the minimum size of 1200x790 pixels." So it is getting the image correctly, it's just not scaling up high enough. And even if it did, on a photo that big do you think the resolution would be bad because of how much up scaling it would have to do?

**Comment by timbuckingham** [comment]
I tested it out with 3000x3000 minimums for some random videos and it still upscaled. Yeah, it does look terrible though. I tested that video out at 1200x790 and it doesn't end up looking too great (assuming you draw it at that size): http://s3.amazonaws.com/BigTreeTestBucket/files/pages/youtube-video-wpwadlgwjea-3.jpg

Are you using the field in a template, module, or setting? Just trying to narrow down where the error might be. I'm testing it in a template successfully. Can you send me a SQL insert statement for whatever it is (whether a row in bigtree_templates, bigtree_settings, or bigtree_module_forms). Thanks!

**Comment by jmason03** [comment]
I'm using it in a module. I did set it up in other places (template and a second module) but did not use an image preset with a min width/height and it all worked correctly. I'm not sure which insert statement you are referring to. Are you wanting the json for the module form or the insert statement for the actual record itself?

**Comment by timbuckingham** [comment]
If it's misbehaving in a module form, the insert statement for the whole row and a CREATE statement for the table I guess. I usually use Sequel Pro where you can right click on a row and do "Copy as SQL Insert".

**Comment by jmason03** [comment]
Ok, here is the insert for that form in bigtree_module_forms and the CREATE statement for bigtree_module_forms table. Let me know if you need anything else!

http://www.drury.edu/web/media-gallery-sql.txt

**Comment by timbuckingham** [comment]
Thanks! I think I have this fixed now. I released 1.4.1 which should auto upgrade smoothly. It also fixes editing an existing video giving an ugly "Awaiting Upload" message when saving.
