### ISSUE TITLE
Field losing values

### ISSUE THREAD

**Issue by benplum** [timbuckingham/bigtree-media-gallery-field-type#5]
The $field param needs to be passed in the draw.php file:

<? BigTreeAdmin::drawArrayLevel(array($current),$item,$field) ?>

**Comment by timbuckingham** [comment]
I think that was fixed in this commit:
https://github.com/timbuckingham/bigtree-media-gallery-field-type/commit/f6a6f590c43b015a8f997dfaed048aa7c81a356b

**Comment by benplum** [comment]
Weird I didn't get an update notice in the admin.

Ben Plum
benplum.com

Sent by an Android
